project:
  type: website
  preview:
    port: 4000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  sidebar:
    style: floating
    contents:
      - href: index.qmd
        text: Home
      - section: Notes
        contents: notes/*
      - section: Tools
        contents: tools/*
      - section: Extras
        contents: extras/*
  favicon: assets/favicon.jpg
  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      - text: "Home"
        href: index.qmd
      - text: "Notes"
        href: notes/index.qmd
      - text: "Tools"
        href: tools/index.qmd
      - text: "Extras"
        href: extras/index.qmd
      - text: "Help"
        menu:
          - text: "Report an Issue"
            icon: bug
            href: https://github.com/mudiarto/mudiarto.github.io/issues

    right:
      - icon: github
        href: "https://github.com/mudiarto"
        aria-label: Mudiarto at Github
      - icon: twitter
        href: https://twitter.com/mudiarto
        aria-label: Mudiarto at Twitter

metadata-files: [nbdev.yml]
